import React, {useState} from "react";
import {languageNames} from "../i18n";

const integrations = [
  {id:"bitrix", name:"Bitrix24", description:"CRM funnel and lead status sync", color:"#16a6df", symbol:"B"},
  {id:"facebook", name:"Facebook / Meta", description:"Ads, videos and Lead Ads analytics", color:"#1877f2", symbol:"f"},
  {id:"amocrm", name:"amoCRM", description:"Leads, deals and sales attribution", color:"#ef6a45", symbol:"a"}
];

function ProviderLogo({item}) { return <span className="provider-logo" style={{"--provider":item.color}}>{item.symbol}</span>; }

export default function Settings({darkMode, setDarkMode, language, setLanguage, t}) {
  const [active, setActive] = useState(null), [saved, setSaved] = useState("");
  const sessionOnly = language === "uz" ? "Faqat shu sessiya uchun saqlandi; server integratsiyasi ulanmagan." : language === "ru" ? "Сохранено только на время сессии; серверная интеграция не подключена." : "Saved for this session only; server integration is not connected.";
  const [bitrixUrl, setBitrixUrl] = useState(""), [funnels, setFunnels] = useState([]), [funnelId, setFunnelId] = useState("");
  const [telegram, setTelegram] = useState(false), [telegramToken, setTelegramToken] = useState(""), [telegramChat, setTelegramChat] = useState(""), [telegramTopic, setTelegramTopic] = useState(""), [reportTime, setReportTime] = useState("09:00"), [reportSaved, setReportSaved] = useState("");
  function loadFunnels() { if (bitrixUrl.startsWith("https://")) setFunnels([{id:"1",name:"Main funnel"},{id:"2",name:"New leads"},{id:"3",name:"Qualified leads"}]); }
  function save(message=t.saved) { setSaved(message); setTimeout(()=>setSaved(""),2500); }
  return <div>
    <div className="page-head"><div><h1>{t.settingsTitle}</h1><p>{t.settingsSub}</p></div></div>
    <section className="panel integration-panel"><div className="section-title"><div><h2>Integrations</h2><p>Choose a service to configure its connection.</p></div><span className="settings-icon">↗</span></div><div className="integration-list">{integrations.map(item=><button key={item.id} className={`integration-card ${active===item.id?"selected":""}`} onClick={()=>setActive(active===item.id?null:item.id)}><ProviderLogo item={item}/><span className="integration-copy"><strong>{item.name}</strong><small>{item.description}</small></span><span className="card-arrow">{active===item.id?"⌃":"›"}</span></button>)}</div></section>
    {active === "bitrix" && <section className="panel settings-panel provider-panel"><div className="settings-heading"><div><h2>Bitrix24</h2><p>{t.bitrixSub}</p></div><span className="integration-status">{t.notConnected}</span></div><form className="settings-form" onSubmit={e=>{e.preventDefault();save(t.connected)}}><label>{t.webhook}<input value={bitrixUrl} onChange={e=>setBitrixUrl(e.target.value)} placeholder={t.webhookPlaceholder} required/></label><div className="funnel-row"><label>{t.funnelId}<select value={funnelId} onChange={e=>setFunnelId(e.target.value)} disabled={!funnels.length}><option value="">{funnels.length?t.required:t.loadFunnels}</option>{funnels.map(f=><option key={f.id} value={f.id}>{f.name} (ID: {f.id})</option>)}</select></label><button type="button" onClick={loadFunnels}>{t.loadFunnels}</button></div><div className="settings-actions"><button type="submit">{t.confirmConnect}</button>{saved&&<span className="saved-message">{saved}</span>}</div></form></section>}
    {active === "facebook" && <section className="panel settings-panel provider-panel"><div className="settings-heading"><div><h2>Facebook / Meta</h2><p>{t.facebookSub}</p></div><span className="integration-status">{t.notConnected}</span></div><form className="settings-form" onSubmit={e=>{e.preventDefault();save(t.connected)}}><div className="two-col"><label>{t.appId}<input required placeholder={t.required}/></label><label>{t.appSecret}<input type="password" required autoComplete="off"/></label><label>{t.adAccount}<input placeholder="act_123456789"/></label><label>{t.pageId}<input placeholder={t.required}/></label></div><label>{t.verifyToken}<input type="password" autoComplete="off"/></label><div className="settings-actions"><button type="submit">{t.connectFacebook}</button>{saved&&<span className="saved-message">{saved}</span>}</div></form></section>}
    {active === "amocrm" && <section className="panel settings-panel provider-panel"><div className="settings-heading"><div><h2>amoCRM</h2><p>Connect amoCRM to sync leads, deals and sales.</p></div><span className="integration-status">{t.notConnected}</span></div><form className="settings-form" onSubmit={e=>{e.preventDefault();save(t.connected)}}><label>Account URL<input type="url" placeholder="https://your-company.amocrm.com" required/></label><label>Client ID<input required placeholder={t.required}/></label><label>Client secret<input type="password" required autoComplete="off"/></label><div className="settings-actions"><button type="submit">{t.confirmConnect}</button>{saved&&<span className="saved-message">{saved}</span>}</div></form></section>}
    <section className="panel settings-panel compact-settings"><div className="settings-heading"><div><h2>{t.language}</h2><p>{t.languageSub}</p></div></div><select className="language-select" value={language} onChange={e=>setLanguage(e.target.value)}>{Object.entries(languageNames).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><div className="theme-options"><button className={!darkMode?"theme-option active":"theme-option"} onClick={()=>setDarkMode(false)}><span>☀️</span><strong>{t.light}</strong><small>{t.clean}</small></button><button className={darkMode?"theme-option active":"theme-option"} onClick={()=>setDarkMode(true)}><span>🌙</span><strong>{t.dark}</strong><small>{t.easy}</small></button></div></section>
    <section className="panel settings-panel compact-settings"><div className="settings-heading"><div><h2>{t.bot}</h2><p>{t.botSub}</p></div><span className="integration-status">{t.notConnected}</span></div><form className="settings-form" onSubmit={e=>{e.preventDefault();setReportSaved(sessionOnly);setTimeout(()=>setReportSaved(""),2500)}}><div className="two-col"><label>{t.botToken}<input type="password" value={telegramToken} onChange={e=>setTelegramToken(e.target.value)} placeholder={t.tokenPlaceholder} autoComplete="off"/></label><label>{t.chatId}<input value={telegramChat} onChange={e=>setTelegramChat(e.target.value)} placeholder={t.chatPlaceholder}/></label><label>Topic ID<small>Telegram forum topic/message thread ID (optional).</small><input inputMode="numeric" pattern="[0-9]*" value={telegramTopic} onChange={e=>setTelegramTopic(e.target.value.replace(/\D/g, ""))} placeholder="e.g. 1234"/></label></div><div className="two-col"><label>{t.dailyReport||"Daily Telegram report"}<small>{t.dailyReportSub||"Send a daily performance summary to Telegram."}</small></label><label>{t.reportTime||"Report time"}<input type="time" value={reportTime} onChange={e=>setReportTime(e.target.value)}/></label></div><label className="switch-row"><span><strong>{t.enableNotifications}</strong><small>{t.notificationSub}</small></span><input type="checkbox" checked={telegram} onChange={e=>setTelegram(e.target.checked)}/></label><div className="settings-actions"><button type="submit">{t.saveReport||t.save}</button>{reportSaved&&<span className="saved-message">{reportSaved}</span>}</div></form></section>
  </div>;
}
